export interface Unit {
  name: string;
  value: number;
}

export const UnitType: Unit[] = [
  { name: "克", value: 1 },
  { name: "千克", value: 2 },
  { name: "两", value: 3 },
  { name: "斤", value: 4 },
  { name: "磅", value: 5 },
  { name: "盎司", value: 6 },
  { name: "毫升", value: 7 },
  { name: "升", value: 8 },
  { name: "寸", value: 9 },
  { name: "厘米", value: 10 },
  { name: "英寸", value: 11 },
  { name: "个", value: 12 },
  { name: "串", value: 13 },
  { name: "枚", value: 14 },
  { name: "粒", value: 15 },
  { name: "块", value: 16 },
  { name: "只", value: 17 },
  { name: "副", value: 18 },
  { name: "卷", value: 19 },
  { name: "片", value: 20 },
  { name: "贯", value: 21 },
  { name: "碗", value: 22 },
  { name: "杯", value: 23 },
  { name: "袋", value: 24 },
  { name: "瓶", value: 25 },
  { name: "盒", value: 26 },
  { name: "包", value: 27 },
  { name: "锅", value: 28 },
  { name: "罐", value: 29 },
  { name: "扎", value: 30 },
  { name: "条", value: 31 },
  { name: "壶", value: 32 },
  { name: "打", value: 33 },
  { name: "盘", value: 34 },
  { name: "1人份", value: 35 },
  { name: "2人份", value: 36 },
  { name: "3人份", value: 37 },
  { name: "4人份", value: 38 },
  { name: "5人份", value: 39 },
  { name: "6人份", value: 40 },
  { name: "7人份", value: 41 },
  { name: "8人份", value: 42 },
  { name: "9人份", value: 43 },
  { name: "10人份", value: 44 },
  { name: "米", value: 45 }
];
